<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Additional Compiled Classes
    |--------------------------------------------------------------------------
    |
    | Here you may specify additional classes to include in the compiled file
    | generated by the `artisan optimize` command. These should be classes
    | that are included on basically every request into the application.
    |
    */

    'files' => [
        app_path('Cms/Cms.php'),
        app_path('Cms/Resource.php'),
        app_path('Cms/Section.php'),
        app_path('Cms/Page.php'),
        app_path('Cms/Toc.php'),
        app_path('Md/Compiler.php'),
        app_path('Md/LinkProcessor.php'),
        app_path('Md/Parser.php'),
        app_path('Link.php'),
        app_path('Navigation.php'),
        app_path('Quicklime.php'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Compiled File Providers
    |--------------------------------------------------------------------------
    |
    | Here you may list service providers which define a "compiles" function
    | that returns additional files that should be compiled, providing an
    | easy way to get common files from any packages you are utilizing.
    |
    */

    'providers' => [
        //
    ],

];
